### ISSUE TITLE
빌드 시 v141을 찾을 수 없다고 나오네요

### ISSUE THREAD

**Issue by ljh1324** [crack-love/KSL#10]
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

v141을 설치하려면  Visual Studio 2017 버전을 설치해야할 것 같네요.

참고: https://stackoverflow.com/questions/44046355/visual-studio-2015-not-detecting-v141-2017-build-tools/44062264

**Comment by crack-love** [comment]
VS2017에서 컴파일했는데 역시 2017 버그가 많네 ㄷㄷ
개발환경 2017로 통일해야 할 듯... 그거 깔고서 해결 되면 알려주셈
