### ISSUE TITLE
opencv_world341d.dll이(가) 없어 코드 실행을 진행할 수 없습니다

### ISSUE THREAD

**Issue by ljh1324** [crack-love/KSL#11]
https://sourceforge.net/projects/opencvlibrary/files/latest/download?source=typ_redirect opencv3.4.1 버전 설치 후 설치 폴더\opencv\build\x64\vc15\bin 에서 opencv_world341.dll, opencv_world341d.dll 복사 후  KSL-0.0.1\x64\Debug 폴더에 붙여넣으면 실행이됩니다.

**Comment by crack-love** [comment]
아 OpenCV 종속성 있었네, world341d는 debug프로그램용 dll이고 그냥 word341.dll(뒤에 d가 안붙어있음)는 release프로그램용이라서 둘 다 필요한데 프로젝트에서 이용하는 환경변수 OpenCV_DIR를 opencv 빌드 폴더 예)'C:\dev\opencv-3.4.1\build' 로 설정하면 둘 다 해결될거임 아마

사용된 버전은 3.4.1임

**Comment by crack-love** [comment]
release 빌드하고 실행해보면 안될거라.. 환경변수 설정해보고 release 실행되는지 알려주셈

**Comment by crack-love** [comment]
다른 환경에서 빌드하고 실행해보니 exe파일 실행에 dll 3총사가 필요한것같음
world341.dll kinect20.dll kinect20.face.dll
이 세 파일이 빌드시에는 프로젝트 설정에서 참조할 수 있지만 바이너리 프로그램은 PATH 환경변수에서 참조할 수 없어서 발생하는 오류로 판단됨

**Comment by crack-love** [comment]
OpenCV_DIR를 환경변수 설정하는 것이 아니라
PATH에 위 3파일을 참조할 수 있도록 해야하는 것으로 보임
